quotes_app/config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  
  get '/about', to: 'static_pages#about'
  get '/imprint', to: 'static_pages#imprint'
  get '/privacy_notice', to: 'static_pages#privacy_notice'
  get '/contact', to: 'static_pages#contact'

  get '/gallery', to: 'static_pages#full_gallery'
  get '/gallery/:id', to: 'gallery#show_quote'
  get '/gallery/*id/download', to: 'gallery#download_quote'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

quotes_app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

quotes_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	def work_in_progress
		render html: "For the Love of Quote - Work in progress"
	end
end

quotes_app/app/controllers/gallery_controller.rb
class GalleryController < ApplicationController
  def gallery
  end

  def show_quote
  	render "#{params[:id]}"
  end

  def download_quote
  	send_file("#{Rails.root.join('app', 'assets', 'images', "/home/anna/ruby/Projekte/twitter_quotes_bot/general/quotes_app/app/assets/images/big_sized_images/#{params[:id]}.jpg")}")
  end
end

quotes_app/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
  end
  
  def about
  end

  def imprint
  end

  def privacy_notice
  end

  def contact
  end

  def full_gallery
  end
end

quotes_app/app/helpers/application_helper.rb
module ApplicationHelper
	
	# Creates a custom title for each page
	def full_title(page_title = '')
		base_title = "For the Love of Quote"
		if page_title.empty?
			base_title
		else
			page_title + ' | ' + base_title
		end
	end
end

quotes_app/app/helpers/gallery_helper.rb
module GalleryHelper
end

quotes_app/app/helpers/static_pages_helper.rb
module StaticPagesHelper

	# Finds all images of jpeg format and adds them to an arry
	def find_images
		all_images = []
		Dir.entries("app/assets/images").each do |el|
			if el[-4..-1] == ".jpg"
				all_images << el
			end
		end
		return all_images
	end

end

quotes_app/app/views/gallery/1.html.erb
<% provide(:title, "H. Jackson Brown, Jr.") %>

<div class="single-quote-img">
<%= link_to image_tag("1.jpg", alt:"quote by H. Jackson Brown, Jr.", class: "quotes-img"), image_url('1.jpg'), target: :_blank %>
</div>

quotes_app/app/views/gallery/13.html.erb
<% provide(:title, "Mike Gafka") %>

<div class="single-quote-img">
<%= link_to image_tag("13.jpg", alt:"quote by Mike Gafka", class: "quotes-img"), image_url('13.jpg'), target: :_blank %>
</div>

quotes_app/app/views/gallery/14.html.erb
<% provide(:title, "Pharell") %>

<div class="single-quote-img">
<%= link_to image_tag("14.jpg", alt:"quote by Pharell", class: "quotes-img"), image_url('14.jpg'), target: :_blank %>
</div>

quotes_app/app/views/gallery/15.html.erb
<% provide(:title, "Unknown") %>

<div class="single-quote-img">
<%= link_to image_tag("15.jpg", alt:"quote by Unknown", class: "quotes-img"), image_url('15.jpg'), target: :_blank %>
</div>

quotes_app/app/views/gallery/2.html.erb
<% provide(:title, "Anthony Robbins") %>

<div class="single-quote-img">
<%= link_to image_tag("2.jpg", alt:"quote by Anthony Robbins", class: "quotes-img"), image_url('2.jpg'), target: :_blank %>
</div>

quotes_app/app/views/gallery/3.html.erb
<% provide(:title, "Randy Pausch") %>

<div class="single-quote-img">
<%= link_to image_tag("3.jpg", alt:"quote by Randy Pausch", class: "quotes-img"), image_url('3.jpg'), target: :_blank %>
</div>

quotes_app/app/views/gallery/4.html.erb
<% provide(:title, "Aristotle") %>

<div class="single-quote-img">
<%= link_to image_tag("4.jpg", alt:"quote by Aristotle", class: "quotes-img"), image_url('4.jpg'), target: :_blank %>
</div>

quotes_app/app/views/gallery/5.html.erb
<% provide(:title, "Unknown") %>

<div class="single-quote-img">
<%= link_to image_tag("5.jpg", alt:"quote by Unknown", class: "quotes-img"), image_url('5.jpg'), target: :_blank %>
</div>

quotes_app/app/views/gallery/6.html.erb
<% provide(:title, "Hugh Downs") %>

<div class="single-quote-img">
<%= link_to image_tag("6.jpg", alt:"quote by Hugh Downs", class: "quotes-img"), image_url('6.jpg'), target: :_blank %>
</div>

quotes_app/app/views/gallery/7.html.erb
<% provide(:title, "Norman Cousins") %>

<div class="single-quote-img">
<%= link_to image_tag("7.jpg", alt:"quote by Norman Cousins", class: "quotes-img"), image_url('7.jpg'), target: :_blank %>
</div>

quotes_app/app/views/gallery/8.html.erb
<% provide(:title, "Ralph Waldo Emerson") %>

<div class="single-quote-img">
<%= link_to image_tag("8.jpg", alt:"quote by Ralph Waldo Emerson", class: "quotes-img"), image_url('8.jpg'), target: :_blank %>
</div>

quotes_app/app/views/gallery/9.html.erb
<% provide(:title, "Thomas J. Watson") %>

<div class="single-quote-img">
<%= link_to image_tag("9.jpg", alt:"quote by Thomas J. Watson", class: "quotes-img"), image_url('9.jpg'), target: :_blank %>
</div>

quotes_app/app/views/layouts/_footer.html.erb
<footer class="footer">
	<nav class="foot-nav">
		<ul class="foot-menu-list">
			<li class ="left-footer"><%= active_link_to fa_icon('twitter', type: :brand), "https://twitter.com/fortheloveofquo", target: "_blank" %></li>
			<li class ="left-footer"><%= active_link_to fa_icon('instagram', type: :brand), "https://www.instagram.com/loving_quotes_again/", target: "_blank" %></li>
			<!-- <li class ="left-footer"><%= active_link_to fa_icon('telegram', type: :brand), "https://t.me/fortheloveofquotes", target: "_blank" %></li> -->
			<li class= "left-footer"><%= active_link_to fa_icon('mastodon', type: :brand), "https://layer8.space/@fortheloveofquote", target: "_blank" %></li>
			<li class = "right-footer" id="imprint"><%= active_link_to "Imprint", imprint_path %></li>
			<li class = "right-footer"><%= active_link_to "Privacy notice", privacy_notice_path %></li>
		</ul>
	</nav>
</footer>

quotes_app/app/views/layouts/_header.html.erb
<header class="header navbar navbar-fixed-top">
  <div class="container-fluid">
    <%= link_to "For the Love of Quote", root_path, id: "logo" %>
    <%= active_link_to fa_icon('bars', type: :solid), "javascript:void(0);", class_active: 'mobile-menu-icon', class_inactive: 'mobile-menu-icon', onclick: "myFunction()" %>
    <nav class="head-nav desktop" id = "head-nav-id">
      <ul class="head-menu-list">
        <li><%= active_link_to "Home",   root_path, active: :exclusive%></li>
        <li><%= active_link_to "Gallery", gallery_path %></li>
        <li><%= active_link_to "About",   about_path %></li>
        <li><%= active_link_to "Contact", contact_path %></li>
      </ul>
       
    </nav>
  </div>

  <script>
    function myFunction() {
      var x = document.getElementById("head-nav-id");
      if (x.className === "head-nav desktop") {
        x.className = "head-nav responsive";
      } else {
        x.className = "head-nav desktop";
      }
    }
  </script>
</header>

quotes_app/app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

quotes_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%=full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  <link rel="stylesheet" type="text/css" href="//wpcc.io/lib/1.0.2/cookieconsent.min.css"/><script src="//wpcc.io/lib/1.0.2/cookieconsent.min.js"></script><script>window.addEventListener("load", function(){window.wpcc.init({"border":"thick","colors":{"popup":{"background":"#f9f9f9","text":"#006994","border":"#006994"},"button":{"background":"#006994","text":"#f9f9f9"}},"position":"bottom-right","corners":"normal","content":{"href":"localhost:3000/privacy_notice"}})});</script>
  <link href="favicon.png" rel="icon">  
  <script src="https://kit.fontawesome.com/44e42f36cb.js" crossorigin="anonymous"></script>
  <%= favicon_link_tag asset_path('quotes_logo_img.ico') %>
  </head>

 <body>
    <%= render 'layouts/header' %>
      <%= yield %>
    <%= render 'layouts/footer' %>
  </body>

</html>

 

quotes_app/app/views/layouts/gallery.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%=full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>

   <body>
    <%= render 'layouts/header' %>
    <div class="single-page single-quote-page">
      <%= yield %> <!-- div class="single-quote-img" link_to image_tag /div -->
      <div class="single-quote-meta">
        
        <div class="single-quote-meta-text">   
          <br>
          License: <%= link_to("CC-BY-SA", "https://creativecommons.org/licenses/")%>
          <br>
          That means you can download, edit and use this image even for commercial purposes as long as you credit me and license your new creation under exact the same terms.
        </div>
        <div class="single-quote-buttons">
          <%= link_to "Download", "#{request.original_url}/download", class: "btn btn-lg btn-primary download-btn"%>

          <form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top" class="donate-btn">
            <input type="hidden" name="cmd" value="_s-xclick" />
            <input type="hidden" name="hosted_button_id" value="BL6WH5GGC76P8" />
            <input type="image" src="https://www.paypalobjects.com/en_US/DK/i/btn/btn_donateCC_LG.gif" border="0" name="submit" title="PayPal - The safer, easier way to pay online!" alt="Donate with PayPal button" class="donate-img" />
            <img alt="" border="0" src="https://www.paypal.com/en_DE/i/scr/pixel.gif" width="1" height="1" />
          </form>
        </div>        
      </div>
    </div>
    <%= render 'layouts/footer' %>
   </body>
 </html>

quotes_app/app/views/layouts/header_desktop_working.html.erb
<header class="header navbar navbar-fixed-top">
  <div class="container-fluid">
    <%= link_to "For the Love of Quote", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav" id="head-nav-id">
        <li><%= active_link_to "Home",   root_path, active: :exclusive %></li>
        <li><%= active_link_to "Gallery", gallery_path %></li>
        <li><%= active_link_to "About",   about_path %></li>
        <li><%= active_link_to "Contact", contact_path %></li>
      </ul>
      <%= active_link_to fa_icon('bars', type: :solid), "javascript:void(0);", class_active: 'mobile-menu-icon', class_inactive: 'mobile-menu-icon', onclick: "myFunction()" %> 
    </nav>
  </div>

<script>
  function myFunction() {
    var x = document.getElementById("head-nav-id");
    if (x.className === "") {
      x.className += " responsive";
    } else {
      x.className = "nav navbar-nav";
    }
  }
</script>
</header>

quotes_app/app/views/static_pages/about.html.erb
<% provide(:title, "About") %>

<div class="single-page about-content">
	<p>
		Hi there,<br>
		I am Anna and I am a big fan of quotes. I think it is amazing how people are able to express a deep thought in just a few words.<br>
		When you read a quote, something inside you may respond. It strikes you because it somehow relates to something that you have experienced or because it shows that great people, successful in their chosen areas believe in same principles as you or show passion for the same values as you do. 
	</p>
	<p> 
		Here are a few quotes that come to my mind when times are tough:
	</p>

	<p>
		<div class="about-quotes">
			"Many  of life's failures are people who did not realise how close they were to success when they gave up." (Thomas Edison)<br>
			"Tough times never last, but tough people do." (Robert H. Schuller)<br>
			"Morning will come. It has no choice." (Marty Rubin)<br>
			"Do what you feel in your heart to be right - for you'll be criticized anyway." (Eleanor Roosevelt)
		</div>
	<p>
		This principle was already known by Aristotle who said:
	</p>
		<div class="about-quotes">					
			"There is only one way to avoid critisism: do nothing, say nothing and be nothing."
		</div>

	</p>

	<p>
		The brilliance in some quotes also lies in their wit and sharpness. They make you smile, smirkle or even laugh.
	</p>

	<p>      
		<div class="about-quotes">
			"I'm a man of simple tastes. I'm always satisfied with the best." (Oscar Wilde)<br>
			"Wine is constant proof that God loves us ans loves to see us happy." (Benjamin Franklin)
		</div>
	</p>

	<p>
		Some quotes keep you on track and motivate you to perceive your goal. These quotes are especially powerful when said by people you admire.
		<div class="about-quotes">				
			"Whatever you are, be a good one." (Abraham Lincoln)<br>
			"Being realistic is the most commonly travelled road to mediocrity." (Will Smith)<br>
			"Stay hungry. Stay foolish." (Steve Jobs)<br>
			"If one advances confidently in the direction of his dreams, and endeavors to live the life he has imagined, he will meet with a success unexpected in common hours." (Herny David Thoreau)
		</div>
	</p>
	<p>
		On this website I try to collect inspirational, thoughtful or just witty and funny quotes. So when I'm in the mood for some motivation, supporting words or a new impuls, I can just come to this website, take some moments and enjoy.
	</p>
	<p style="text-align: right; font-style: italic;">
		Anna
	</p>
</div>

quotes_app/app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>

<div class="single-page contact-content">
	<h3>Contact me</h3>
	<p>If you have any ideas, questions or if you want to share some quotes that you like, please send me an email to <a href="mailto:fortheloveofquote@protonmail.com" class="mailto">fortheloveofquote@protonmail.com</a></p>

</div>

quotes_app/app/views/static_pages/full_gallery.html.erb
<% provide(:title, "Gallery")%>

<div class="gallery-content">
	<% find_images.each do |img| %>
			<%= link_to image_tag(img, alt: "quote_#{img}", class: "gallery-img"), "#{request.original_url}/#{img.delete_suffix('.jpg')}" %>
	<% end %>
</div>

quotes_app/app/views/static_pages/home.html.erb
<div class="center home-content">
	<% find_images.each do |img|%>
		<%= image_tag(img, alt: "quote", class: 'mySlides') %>
	<% end %>
    
</div>

<button class="quotes_button prev" onclick="plusSlides(-1)"><i class="fas fa-chevron-left"></i></button>
<button class="quotes_button next" onclick="plusSlides(+1)"><i class="fas fa-chevron-right"></i></button>

<script>
	var slideIndex = 0;
	var t;
	carousel(slideIndex);

	function plusSlides(n) {
		clearTimeout(t);
		carousel(slideIndex += n);
	}

	function carousel(n) {
		clearTimeout(t);
		var i;
		var x = document.getElementsByClassName("mySlides");
		for(i = 0; i < x.length; i++) {
			x[i].style.display = "none";
		}

		if (n >= x.length) {
			slideIndex = 0;
		} else if (n < 0) {
			slideIndex = x.length -1;
		} else {
			slideIndex = n;
		}
		x[slideIndex].style.display = "block";
		t = setTimeout(function() {carousel(slideIndex += 1);}, 10000);
	}
</script>

quotes_app/app/views/static_pages/imprint.html.erb
<% provide(:title, "Imprint") %>

<div class="single-page imprint-content">
	<h3>Imprint</h3>
	<p>
		Information in accordance with § 5 TMG (German Telemedia Act):
	</p>
	<p>
		Anna Förster<br>
		Hofmarktstraße 42<br>
		82152 Planegg<br><br>
		email: <a href="mailto:fortheloveofquote@protonmail.com" class="mailto">fortheloveofquote@protonmail.com</a>
	</p>

</div>

quotes_app/app/views/static_pages/p1.html.erb
<div class="single-page p1">
	<p>
		Just a test for p1-url
	</p>
	
	<div class="mybutton">
		<%= link_to "Download", "#{request.original_url}/download" %>
	</div>
</div>